### PR TITLE
Improved experimental UI addresses #93

### PR DESCRIPTION
**Pull request by AMacro**
Experimental UI can now be instantiated correctly.

More work required to make it useful (so far just cosmetic/framework has been completed).

These commits are part of an experiment to allow trains to exchange passengers at interchange/transfer stations.

image
image

### CODE REVIEW

**Comment by AdamC1228** [comment]
This is very much along the lines of the implementation I was thinking of for the experimental UI to solve a lot of the issues with the Cochran and Alarka depot routing issues but with one difference. I was envisioning something nearly identical (and maybe its just not in your screenshots) but you would have an add button to add a new row where you can choose a station from the list. This would eliminate a lot of the complex and somewhat hackish workarounds that we have in place or are considering putting in place to solve the issue with the branch line(s).

This is more or less what I was trying to build but had not yet determined how to build. Either way I will definitely be looking forward to digging into your pr tomorrow. 

image

**Comment by AMacro** [comment]
My friend and I were talking about doing that for phase 2

phase 1: get it working more or less as it currently does
phase 2: exactly what you described

**Comment by AMacro** [comment]
So far, the UI appears to be doing its job, the routing *mostly* works with a minor issue, yet to be resolved.

- If a station is set for pickup and is also set as a stop, there's no need to set a transfer station (dropdown removed[^1]).
- If a station is set for pickup but is not a stop, a transfer station should be selected (not yet enforced), otherwise passengers will go on a never-ending scenic loop.
- If a station is set as a transfer station (e.g. in the screenshot, Wilmot is a transfer station for Whittier and Ela), then that station must also be a stop - this is enforced in the UI, so to remove Wilmot as a stop, both Whittier and Ela would need to be stops or assigned a different transfer station.

Outstanding issue - in testing, everything worked as expected travelling west. Once the end of line was reached, the Hemmingway and Alarka passengers were re-collected prior to departing Bryson for Wilmot.

Being 10:30 PM here (GMT+10:30), I'll revisit this issue after work tomorrow and will hopefully have a further commit to resolve it. 

image

[^1]:Currently not visually appealing, but fixable.

**Comment by AdamC1228** [comment]
Just a few notes / changes that I have after skimming the git-hub change logs but overall I like what I see. 

- The multiplayer broadcast changes should be their own pull request for tracking / discussion purposes. On that same note, it would be better to instead have an experimental flag / mod setting to enable / disable the multiplayer broadcast options. Perhaps something like the mock ups below. 
image
image


- Instead of gutting / altering the existing methods for the code that currently controls everything, Id ask that even if it means duplicating certain methods and giving them an _dev at the end of the function name or outright changing the function names, that we ensure that the existing code / approach remains functioning. Since this significantly changes the core behaviors / functions both new and old should be able to be toggled on and off until at least 2.2. Again, this means that there will be some duplicated / redundant code but I think with as significant a change as this is, it warrants the extra effort of maintaining both for now.

**Comment by AMacro** [comment]
> The multiplayer broadcast changes should be their own pull request for tracking / discussion purposes.

Agreed - the broadcast wasn't supposed to be part of these commits - will remove

> Instead of gutting / altering the existing methods for the code that currently controls everything, Id ask that even if it means duplicating certain methods and giving them an _dev at the end of the function name or outright changing the function names, that we ensure that the existing code / approach remains functioning

Agreed - will update accordingly

**Comment by AMacro** [comment]
Changes are now ready for testing/merging. Early testing indicates it may play ok with the game's new passenger AI mode, but further testing required.

Issues fixed in the dev functions (still exist in non/experimental mode):
- Locomotive now knows which way to move when pulling out from the station - no longer goes in the wrong direction
- Finding the closest station now uses the track distance, not 'as-the-crow-flies' - this fixes the issue that occurs between Bryson and Alarka Jct[^1] where the track shape may result in the wrong station being the closest e.g. at mile 65, 'as-the-crow-flies' Hemmingway is closest, but by track, Bryson is closer.
- Ensures passengers load/unload when initialising the AutoEngineer
- If starting AutoEngineer between stations and the locomotive is heading to the wrong station, disabling and re-enabling the AutoEngineer (untick/tick route mode) will flip the direction of travel

Above fixes were required to get the new routing method to work.

All changed functions should now be in their own _dev version except where it doesn't make sense e.g. Dispatcher.Update() now has selection based on new UI mode that will start the _dev coroutrine or the original coroutine.


image

[^1]: May occur at other places too.

**Comment by AdamC1228** [comment]
FYI: Alarka JCT (Pickup & Stop) -> Hemingway (Pickup & Stop). Loco departs hemingway torward bryson and fails to reverse. Passenger stops not copied to coaches. 

Something is not quite right yet. Only had a few moments to sit down and look it over.

**Comment by AMacro** [comment]
I thought it was working, but, you're correct there still appears to be an issue.
I'm wondering if we can use the inbuilt Graph, Searcher and RouteSearcher classes to help determine the direction/switches when moving off the main branch, or worst case, enumerate switches between loco and destination and determine if leaving the mainline and if the switch is incorrectly set announce "waiting for switch".

**Pull request merged**
